version: '3.3'
services:
  mysql-server:
    image: mysql/mysql-server
    restart: on-failure
    environment:
      MYSQL_DATABASE: 'springAuth'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
      # Where our data will be persisted
    volumes:
      - mysql-db:/var/lib/mysql
# Names our volume
volumes:
  mysql-db: